module.exports = {
  AUTHENTICATED: 'AUTHENTICATED',
  CONNECTION_OPENED: 'CONNECTION_OPENED',
  CONNECTION_FAILURE: 'CONNECTION_FAILURE',
  MESSAGE: 'MESSAGE',
  REACTION_ADDED: 'REACTION_ADDED',
  REACTION_REMOVED: 'REACTION_REMOVED'
};
